### ISSUE TITLE
Empty title lines?

### ISSUE THREAD

**Issue by oakmac** [oakmac/kidif.js#2]
What should we do about title lines that have no text other than the delimiter?

**Comment by shaunlebron** [comment]
I can see someone doing this:

```
=====
item1
=====
item2
=====
item3
=====
item4
```

resulting in:

``` js
{
  "": ["item1", "item2", "item3", "item4"]
}
```

It wouldn't be unreasonable to return this instead, if the only key is an empty string:

``` js
["item1", "item2", "item3", "item4"]
```

not crazy about this idea, but something to think about

**Comment by oakmac** [comment]
I think the simplest thing to do is to require title lines to have at least some text after the delimiter.

If a line just has the delimiter and no text after, then it is not a title line and is treated like any other line in a section.

**Comment by shaunlebron** [comment]
:+1:
